# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"\xae\x01\n\x0bOrder_Proto\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\norder_date\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x02\x12+\n\x0border_items\x18\x05 \x03(\x0b\x32\x16.order.OrderItem_Proto\x12\'\n\x08shipment\x18\x06 \x01(\x0b\x32\x15.order.Shipment_Proto\"m\n\x0fOrderItem_Proto\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0btotal_price\x18\x05 \x01(\x02\"`\n\x0eShipment_Proto\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x15\n\rshipment_date\x18\x02 \x01(\t\x12\x15\n\rdelivery_date\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER_PROTO._serialized_start=23
  _ORDER_PROTO._serialized_end=197
  _ORDERITEM_PROTO._serialized_start=199
  _ORDERITEM_PROTO._serialized_end=308
  _SHIPMENT_PROTO._serialized_start=310
  _SHIPMENT_PROTO._serialized_end=406
# @@protoc_insertion_point(module_scope)
